### ISSUE TITLE
Line length passed by user is not being obeyed

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/snakefmt#10]
We currently just use the default https://github.com/mbhall88/snakefmt/blob/12928489794ff4cdcd5626aa36fa8696e20519da/snakefmt/parser/syntax.py#L8

Adding as a class member variable to `Formatter` seems the best solution.

**Comment by bricoletc** [comment]
308429c179e8185baf4b127885a736c5a9fb8281 passes line_length from Formatter to calls to `black`
