### ISSUE TITLE
Whitespace at indent level 0

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/snakefmt#11]
Add newlines

(This is migrated from `TODO.rst`). Perhaps @bricoletc could provide some more context?

**Comment by bricoletc** [comment]
308429c179e8185baf4b127885a736c5a9fb8281 completes placing:
- 2 newlines before each 0-indented keyword (eg rule)
- no newlines between 1+ indented keywords
- 1 newline before each chunk of 0-indented python code
