### ISSUE TITLE
Distinguish parsing from formatting

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/snakefmt#13]
Have code distinguish parsing (and syntax validation) from formatting and compiling. Parsing needs to run successfully before either.

*(Migrated from `TODO.rst` - @bricoletc may want to add more context?)*

**Comment by bricoletc** [comment]
This is especially relevant if we want a single parser in Snakemake. The Parser class reads through Snakefile and checks for syntax errors, and calls abstract methods overriden by our Formatter.

In a similar way we could have a derived Compiler to compile the same code as https://github.com/snakemake/snakemake/blob/master/snakemake/parser.py

**Comment by bricoletc** [comment]
This is now (8d5a5c2b2fdb5e1918285b37e51382cd261f6b10) the case
