### ISSUE TITLE
Grammar issue?

### ISSUE THREAD

**Issue by johanneskoester** [mbhall88/snakefmt#17]
It seems like the grammar does not always correctly detect the right context.
[This](https://github.com/snakemake-workflows/dna-seq-varlociraptor/blob/master/workflow/rules/mapping.smk#L10) statement leads, although perfectly valid, to an error:
```
snakefmt.exceptions.InvalidParameterSyntax: L10: Over-indented recognised keyword found: 'input'
```

I guess the same might happen with `output:` or other stuff occurring outside of the normal context?

**Comment by bricoletc** [comment]
Hi @johanneskoester, thanks for spotting this! 

4d947f2ebbe745477177f3ef1c896e833098a3e4 solves it. The parsing relies on ',' to delimit parameters, so I've made an explicit provision in the context of `lambda` (and also parentheses, eg `expand()`).

Can you think of any other situation where this strategy might fail?

**Comment by bricoletc** [comment]
It still fails on another lambda `        obs=lambda w, input: ["{}={}".format(s, f) for s, f in zip(get_group_aliases(w), input.obs)]
`

**Comment by bricoletc** [comment]
4c24468f401e46a40e0572603bfb3e1127f35ce9 deals with that complex lambda

**Comment by johanneskoester** [comment]
I have another issue:
```
Formatting workflow/rules/tmb.smk:
snakefmt.exceptions.InvalidPython: The following was treated as python code to format with black:
```
if config["tmb"]["activate"]:
	 rule estimate_tmb:
		 input:
"results/calls/{group}.annotated.bcf"
		 output:
"results/plots/tmb/{group}.tmb.vl.json"
		 log:
"logs/estimate-tmb/{group}.log"
		 params:
**			 config["tmb"]
		 conda:
"../envs/varlociraptor.yaml"
		 shell:
"varlociraptor estimate tmb "
"--coding-genome-size {params.coding_genome_size} "
"--somatic-tumor-events {params.somatic_events} "
"--tumor-sample {params.tumor_sample} "
"< {input} > {output} 2> {log}"
```

Rules can be encapsulated in `if`, `else` `for` and `while`. In theory arbitrary nesting is possible.

**Comment by mbhall88** [comment]
Thanks for finding these corner cases @johanneskoester . 😅

**Comment by johanneskoester** [comment]
Another one:
```
SyntaxError: L10: Unrecognised keyword 'cache' in rule download_snpeff_db definition
```

THis is very new, not added to the official grammar yet.

**Comment by bricoletc** [comment]
> I have another issue:
> 
> ```
> Formatting workflow/rules/tmb.smk:
> snakefmt.exceptions.InvalidPython: The following was treated as python code to format with black:
> 
> if config["tmb"]["activate"]:
> 	 rule estimate_tmb:
> 		 input:
> "results/calls/{group}.annotated.bcf"
> 		 output:
> "results/plots/tmb/{group}.tmb.vl.json"
> 		 log:
> "logs/estimate-tmb/{group}.log"
> 		 params:
> **			 config["tmb"]
> 		 conda:
> "../envs/varlociraptor.yaml"
> 		 shell:
> "varlociraptor estimate tmb "
> "--coding-genome-size {params.coding_genome_size} "
> "--somatic-tumor-events {params.somatic_events} "
> "--tumor-sample {params.tumor_sample} "
> "< {input} > {output} 2> {log}"
> ```
> 
> Rules can be encapsulated in `if`, `else` `for` and `while`. In theory arbitrary nesting is possible.

Since c726c17 this is now possible !

**Comment by bricoletc** [comment]
> Another one:
> 
> ```
> SyntaxError: L10: Unrecognised keyword 'cache' in rule download_snpeff_db definition
> ```
> 
> THis is very new, not added to the official grammar yet.

This is now enforced, and tests have been added that will fail if the grammar does not match snakemake's

**Comment by johanneskoester** [comment]
I guess this can be closed then.
