### ISSUE TITLE
Parser is handling some formatting

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/snakefmt#21]
The [`process_keyword`](https://github.com/mbhall88/snakefmt/blob/5970f1536ee24d39d8eb9a9d420bbf8d467e365d/snakefmt/parser/parser.py#L104) method on the `Parser` is doing some formatting, which is the job of `Formatter`.  
https://github.com/mbhall88/snakefmt/blob/5970f1536ee24d39d8eb9a9d420bbf8d467e365d/snakefmt/parser/parser.py#L110

**Comment by bricoletc** [comment]
great spot- this is now fixed and formatting is entirely delegated to `formatter.py`
